-- insert into tb_pet_type (id, i18nplaceholder, name) values (nextval('tb_pet_type_id_seq'), 'pettype.dog', 'dog');
-- insert into tb_pet_type (id, i18nplaceholder, name) values (nextval('tb_pet_type_id_seq'), 'pettype.cat', 'cat');
--
-- insert into tb_req_type (id, description, i18nplaceholder) values (nextval('tb_req_type_id_seq'), 'adoption term', 'adoption.term');
-- insert into tb_req_type (id, description, i18nplaceholder) values (nextval('tb_req_type_id_seq'), 'home pictures', 'home.pictures');
--
--
--
-- insert into tb_pet_tb_req_type (tb_pet_id, reqtypeset_id) values (1, 1);
-- insert into tb_pet_tb_req_type (tb_pet_id, reqtypeset_id) values (1, 2);